services:
  - type: web
    name: iac33-backend
    env: docker
    plan: free
    region: oregon
    buildCommand: docker build -t c33-backend .
    startCommand: uvicorn src.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MODEL_NAME
        value: gpt-4o
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEYS
        sync: false
      - key: PORT
        value: 10000
